### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by rmatsum836** [mattwthompson/scattering#35]
This package is now being used for publication research, so it would be nice to add CI and potentially publish the package to conda-forge.

It may be easiest to transfer ownership to the group organization to accomplish this.

**Comment by mattwthompson** [comment]
Fine by me - assume you mean https://github.com/ptc-cmc?

I can do/contribute to this over the weekend, but if you'd like to get started I'd recommend either copying over the AZP setup from the other repos or use GitHub Actions with https://github.com/conda-incubator/setup-miniconda

**Comment by rmatsum836** [comment]
Yep I was referring to `ptc-cmc` if that's okay with you.

Do you have a preference for using AZP or GitHub actions?  Shouldn't be too difficult for me to setup either way.

**Comment by rmatsum836** [comment]
Addressed in #39 and #40.
