### ISSUE TITLE
Better distance calculations in compute_dynamic_rdf

### ISSUE THREAD

**Issue by mattwthompson** [mattwthompson/scattering#4]
As far as I can tell, `md.compute_distances` would have a tough time computing distances across different frames, which is required for the internals of the dynamic structure factor. However, it is very fast and handles with PBC, neither of which are characteristic of how it is implemented at the moment.

**Comment by mattwthompson** [comment]
Closed by #7 but moreso depends on the status of https://github.com/mdtraj/mdtraj/pull/1423

**Comment by rmatsum836** [comment]
This has subsequently been handled in MDTraj.
